### ISSUE TITLE
New domain and path

### ISSUE THREAD

**Issue by horihiro** [patridge/learn-metadata-tool#84]
Hello @patridge, Thank you for your great tool!

Recently the Microsoft Docs domain changed from `docs.microsoft.com` to `learn.microsoft.com`.
On the other hands, this tool seems to work on `docs.microsoft.com` only according to the [`manifest.json`](https://github.com/patridge/learn-metadata-tool/blob/main/manifest.json#L11)

As a result, the tool doesn't work appropreately.

Could you please look into this?

Thanks,

**Comment by patridge** [comment]
Thanks for reporting this. I'll see if I can find the issue and get it resolved as soon as I can.

**Comment by horihiro** [comment]
Added screenshot for an issue I saw when trying to get metadata of the following page
https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata
![image](https://user-images.githubusercontent.com/4566555/191110220-c4ef3d6b-0af2-4e7e-b575-6504c9cf477e.png)

**Comment by patridge** [comment]
Looks like it's both the manifest as well as a dozen different places with an assumed URL format. Got a good start, but I worry that the new extension manifest v3 requirement from Google will prevent publishing without finishing up some work from the [manifest-v3](https://github.com/patridge/learn-metadata-tool/tree/manifest-v3) branch.

**Comment by patridge** [comment]
Yeah...not looking promising that I'll be able to avoid the manifest upgrade.
https://developer.chrome.com/docs/extensions/mv3/intro/#start-the-conversion

**Comment by patridge** [comment]
I submitted a version that should work but is manifest v2, expecting it to auto-reject. So far, it's just in the queue like normal. If it gets through, I'll merge and update the last bits like normal.

**Comment by patridge** [comment]
With the manifest v3 changes in #86 merged, I'll spin up a second new submission that should be much more likely to pass submission approval.

**Comment by patridge** [comment]
The manifest v2 version was somehow accepted and published for v0.7.9. Folks with auto-update enabled should already be seeing the fixed version working on rebranded Learn URLs. I'll still plan to publish the manifest v3 migration, though, since it's bound to be a blocker at some point.
